### ISSUE TITLE
ActualVim on windows

### ISSUE THREAD

**Issue by m247support** [lunixbochs/ActualVim#115] opened 2017-08-14 13:53 UTC
Just wondering what everyone's thoughts might be?
~~~
Sublime Build 3083
ActualVim v0.9.11
Neovim v0.2
Windows 10
~~~
~~~
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\neo.py", line 80, in plugin_loaded
    vim._setup()
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\neo.py", line 127, in _setup
    self.nv = neovim.attach('child', argv=[NEOVIM_PATH, '--embed', '-n'] + args)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\__init__.py", line 100, in attach
    child_session(argv) if session_type == 'child' else
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\__init__.py", line 42, in child_session
    return session('child', argv)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\event_loop\base.py", line 83, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\event_loop\asyncio.py", line 101, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\windows_events.py", line 373, in _make_subprocess_transport
    **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\base_subprocess.py", line 39, in __init__
    stderr=stderr, bufsize=bufsize, **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\windows_events.py", line 757, in _start
    bufsize=bufsize, **kwargs)
  File "C:\Users\<user>\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\windows_utils.py", line 204, in __init__
    stderr=stderr_wfd, **kwds)
~~~
~~~
{
	"bufopts":
	{
		"completefunc": "ActualVimComplete"
	},
	"enabled": true,
	"indent_priority": "sublime",
	"large_file_disable":
	{
		"bytes": 52428800,
		"lines": 50000
	},
	"neovim_args":
	[
		"--cmd",
		"let g:actualvim = 1"
	],
	"neovim_path": "/C/Program\\ Files/Neovim/bin/nvim.exe",
	"settings":
	{
		"sublime":
		{
			"inverse_caret_state": false
		},
		"vim":
		{
			"bell":
			{
				"color_scheme": "Packages/ActualVim/Bell.tmTheme",
				"duration": 0.001
			},
			"inverse_caret_state": false,
			"modes":
			{
				"all insert":
				{
				},
				"all visual":
				{
				},
				"command":
				{
					"inverse_caret_state": true
				},
				"insert":
				{
				},
				"normal":
				{
					"inverse_caret_state": true
				},
				"replace":
				{
				},
				"visual":
				{
				},
				"visual block":
				{
				},
				"visual line":
				{
				}
			}
		}
	}
}
~~~

**Comment by m247support** [comment] 2017-08-14 13:56
Oh, the issue is that ActualVim is failing to start completely.

**Comment by lunixbochs** [comment] 2017-08-14 15:05
Your traceback is incomplete.

**Comment by lunixbochs** [comment] 2017-08-14 15:06
`/C/Program\\ Files/Neovim/bin/nvim.exe` looks like a bad path. Paths on windows typically look like `C:\\Program Files\\Neovim\\bin\\nvim.exe`

**Comment by lunixbochs** [comment] 2017-08-14 15:07
If Neovim is there, you should just be able to set neovim_path to `""`, as ActualVim already searches that path.

**Comment by m247support** [comment] 2017-08-14 15:38
Thanks a lot @lunixbochs! I corrected the path  and I am no longer getting the trackback in console, but I am now getting:
~~~
reloading plugin ActualVim.actual
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\robert.stanistreet\AppData\Roaming\Sublime Text 3\Packages\ActualVim\actual.py", line 65, in <module>
    class ActualViewListener(sublime_plugin.ViewEventListener):
AttributeError: 'module' object has no attribute 'ViewEventListener'
reloading plugin ActualVim.edit
reloading plugin ActualVim.neo
reloading plugin ActualVim.screen
reloading plugin ActualVim.settings
reloading plugin ActualVim.view
...
ActualVim: using nvim binary path: C:\Program Files\Neovim\bin\nvim.exe
ActualVim: nvim started in 231.84ms
...
ActualVim: request "enter" failed: buf:1 has no view
~~~
This issue is still persisting. Am I correct in understanding that I need to disable the Vintage plugin?

**Comment by lunixbochs** [comment] 2017-08-14 15:54
try restarting sublime if you haven't yet

**Comment by m247support** [comment] 2017-08-14 15:58
Thanks! I have tried restarting Sublime, but unfortunately no luck so far.

**Comment by lunixbochs** [comment] 2017-08-14 23:17
3083 is a little old. I'm on 3126. In the console, does `import sublime_plugin; sublime_plugin.ViewEventListener` work for you?

**Comment by m247support** [comment] 2017-08-15 13:01
Thanks, I'll try updating sublime.

**Comment by m247support** [comment] 2017-10-29 07:38
Hi,

Working nicely with build 3126. Thanks for all your efforts on this awesome plugin!

One slight piece of confusion is that I seem to have lost the ability to copy highlighted text to clipboard via ctrl+c. The same with vim commands y and d in visual mode. I can right click and select copy, or alt e -> c to copy.

This is only really a minor gripe, but I am wondering if anyone has some thoughts or a possible work around? 

Thanks in advance!

**Comment by lunixbochs** [comment] 2017-10-29 16:05
Duplicate of https://github.com/lunixbochs/ActualVim/issues/126

Basically Ctrl is a valid hotkey in Vim.

**Closed** 2017-10-31 08:08 UTC
