### ISSUE TITLE
Add toggle enable command

### ISSUE THREAD

**Issue by simobiggs** [lunixbochs/ActualVim#143] opened 2018-01-31 17:36 UTC
This is a small QoL change request.
Currently there is an ActualVim enable and disable command. This means you need to assign two shortcuts to toggle it. If there was an ActualVim toggle enable command you could use one. The image shows how I currently toggle ActualVim, it would be nice if I could simply press Ctrl+F1 to enable/disable.
![example](https://user-images.githubusercontent.com/8716193/35637797-ed68f8d2-067a-11e8-9885-4593e5e9f41b.PNG)

**Comment by lunixbochs** [comment] 2018-01-31 17:55
Bind the same key to both, the command disables itself when it's not relevant.

**Comment by simobiggs** [comment] 2018-01-31 19:00
If I do like below disable works but not enable.
![image](https://user-images.githubusercontent.com/8716193/35641726-982a2ccc-0686-11e8-9d81-cf2dfec8c37f.png)
Similarly, swapping the order causes enable to work but not disable.

**Comment by lunixbochs** [comment] 2018-01-31 19:20
Oh, that's an issue in Sublime, you need to put the scope on the keymap itself so they don't conflict, sorry!
This is an example:
```
    { "keys": ["ctrl+s"], "context": [{"key": "setting.actual_mode", "operand": true}],  "command": "actual_disable"},
    { "keys": ["ctrl+s"], "context": [{"key": "setting.actual_mode", "operand": false}], "command": "actual_enable"},
```

**Comment by lunixbochs** [comment] 2018-01-31 19:21
This is also a duplicate of https://github.com/lunixbochs/ActualVim/issues/63

**Closed by lunixbochs** 2018-01-31 19:21 UTC
