### ISSUE TITLE
zz and relative numbers

### ISSUE THREAD

**Issue by carlosvigil** [lunixbochs/actualvim#78] opened 2017-03-16 15:11 UTC
I remap j and k to jzz and kzz to center the line on the screen. While not necessary it's progress towards complete Vim.

With that I also benefit from relative line numbers.
[VintageLines](https://github.com/co-dh/VintageLines)

**Comment by lunixbochs** [comment] 2017-03-16 15:15
I think what you want here is - an option to make sure the sublime cursor and screen position completely align with the vim position. I can do this as a default.

**Comment by lunixbochs** [comment] 2017-03-16 16:03
Closing as duplicate of #62. Let me know if you need help integrating with VintageLines.

**Closed by lunixbochs** 2017-03-16 16:03 UTC
Labels: duplicate

**Comment by carlosvigil** [comment] 2017-03-16 16:26
for posterity
as of VintageLines 0.5, to show ordered lines numbers enable Sublime line_numbers.

```
"modes":
{
  "all insert":
    {
      "line_numbers": true,
      "vintage_lines.force_mode": false
    },
    "normal":
    {
      "inverse_caret_state": true,
    },
}
```

**Comment by lunixbochs** [comment] 2017-03-16 16:33
What about visual mode?

**Comment by carlosvigil** [comment] 2017-03-16 16:36
Just an example. I'll have to learn how that plugin works or submit an issue. It doesn't show numbers if it's off
